# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='funding goal'),
        ),
    ]
