# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0002_auto_20160301_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_service_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='payment service provider'),
        ),
    ]
