# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0003_donation_payment_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_reward_required',
            field=models.BooleanField(default=False, verbose_name='is reward required?'),
        ),
    ]
